[build]
  command = "npm install --include=dev && npm run build"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
  [[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

